# -----------------------------Try and Except--------------------

# try:
#     print(x)
# except NameError:
#     print("It comes under name_error")
# except:
#      print("An exception occurred")

#  Finally

# try:
#     print(x)
# except NameError:
#     print("It comes under name_error")
# except:
#      print("An exception occurred")
# finally:
#     print("Finally executed finally")

